name = "test01-phg-music-server"
main = "src/index.ts"
compatibility_date = "2024-08-05"
compatibility_flags = [ "nodejs_compat" ]

[ai]
binding = "AI"


[vars]
API_KEY = "c5cb88052fcfc21ee4a48ab7e3d3d964"
PUBLIC_KEY = "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6"
AI_MODEL = "@cf/qwen/qwen3-30b-a3b-fp8"

[[d1_databases]]
binding = "DB"
database_name = "cf-phg-music-db"
database_id = "5515a37a-2d29-4824-9892-dd7edd6aa450"
